dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('df_user.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'', include('df_goods.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^order/', include('df_order.urls')),
    # url(r'^search/', include('haystack.urls')),


]

df_cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Cart),
    url(r'^add(\d+)_(\d+)/$', views.Add),
    url(r'^edit(\d+)_(\d+)/$', views.Edit),
    url(r'^delete(\d+)/$', views.Delete),
]

df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'register/$', views.register),
    url(r'register_handle/$', views.register_handle),
    url(r'register_exist/$', views.register_exist),
    url(r'login/$', views.Login),
    url(r'login_handle/$', views.Login_handle),
    url(r'info/$', views.Info),
    url(r'order/$', views.order),
    url(r'site/$', views.Site),
    url(r'logout/$', views.Logout),
]

df_order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.UserInfo')
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=7, decimal_places=2)
    oaddress = models.CharField(max_length=150)

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    count = models.IntegerField()

df_user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    usjname = models.CharField(max_length=20, default='')
    uaddress = models.CharField(max_length=100, default='')
    upost = models.CharField(max_length=6, default='')
    umobile = models.CharField(max_length=11, default='')
    # default,blank是Python层面的约束，不影响数据库结构，所以不用迁移

df_user/views.py
#coding=utf-8
from __future__ import unicode_literals
import hashlib
from django.shortcuts import render,redirect
from models import *
from df_goods.models import *
from df_order.models import *
from django.http import JsonResponse, HttpResponseRedirect
from user_decorator import login

def register(request):
    context = {'title': '用户注册'}
    return render(request, 'df_user/register.html', context)

def register_handle(request):
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    upwd2 = post.get('cpwd')
    uemail = post.get('email')

    if uname == '' or upwd == '' or upwd2 == '' or uemail == '':
        return redirect('/user/register/')

    if upwd != upwd2:
        return redirect('/user/register/')
        print('pwd error')
    s1 = hashlib.sha1()
    s1.update(upwd)
    upwd3 = s1.hexdigest()

    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    user.save()

    return redirect('/user/login/')

def register_exist(sequest):
    uname = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count':count})

def Login(request):
    uname = request.COOKIES.get('uname', '')
    context={'title': '用户登录','error_name':0,'error_pwd':0,'uname':uname}
    return render(request, 'df_user/login.html', context)

def Login_handle(request):
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    jizhu = post.get('jizhu',0)

    users = UserInfo.objects.filter(uname=uname)

    if len(users) == 1:
        s1 = hashlib.sha1()
        s1.update(upwd)
        if s1.hexdigest() == users[0].upwd:
            url = request.COOKIES.get('url', '/')
            red = HttpResponseRedirect(url)

            if jizhu != 0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            print request.session['user_name']
            return red
        else:
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
            return render(request, 'df_user/login.html', context)
    else:
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
        return render(request, 'df_user/login.html', context)

def Logout(request):
    request.session.flush()
    return redirect('/')

@login
def Info(request):
    user_email = UserInfo.objects.get(id=request.session['user_id']).uemail
    # 最近浏览
    goods_ids = request.COOKIES.get('goods_ids', '')
    goods_idsl = goods_ids.split(',')
    # GoodsInfo.objects.filter(id__in=goods_idsl) #一次查询所有id,但按id来排序
    goods_list = []
    if goods_ids != '':
        for goods_id in goods_idsl:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))

    context = {'title': '用户中心',
               'user_email': user_email,
               'user_name': request.session['user_name'],
               'page_name': 1,
               'goods_list': goods_list,
               'option': 1}
    return render(request, 'df_user/user_center_info.html', context)

@login
def order(request):
    """
    此函数用户给下订单页面展示数据
    接收购物车页面GET方法发过来的购物车中物品的id，构造购物车对象供订单使用
    """
    uid = request.session.get('user_id')
    user = OrderInfo.objects.filter(user=uid)
    # 获取勾选的每一个订单对象，构造成list，作为上下文传入下单页面
    orderlist = []
    for order in user:
        orderlist.append(order)

    context = {'title': '用户中心', 'page_name': 1, 'option': 2, 'orderlist': orderlist}
    return render(request, 'df_user/user_center_order.html', context)
@login
def Site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == "POST":
        post = request.POST
        user.usjname = post.get('ushou')
        user.uaddress = post.get('uaddress')
        user.upost = post.get('uyoubian')
        user.umobile = post.get('uphone')
        user.save()
    context = {'title': '用户中心', 'user': user, 'page_name': 1, 'option': 3}
    return render(request, 'df_user/user_center_site.html', context)

templates/df_user/login.html
{% extends 'base_foot.html' %}

{% block head %}
    <script>
        $(function () {
            name_error=false;
            pwd_error=false;
            if ({{ error_name }}==1){
                $('.user_error').html('用户名错误').show();
			}
			if ({{ error_pwd }}==1){
                $('.pwd_error').html('密码错误').show();
			}
			$('.name_input').blur(function(){
				if ($('.name_input').val().length==0){
				    $('.user_error').html('请填写用户名').show();
				    name_error=false;
				}else{
				    $('.user_error').hide();
				    name_error=true;
				}
            });
            $('.pass_input').blur(function () {
				if ($(this).val().length==0){
				    $('.pwd_error').html('请输入密码').show();
				    pwd_error=false;
				}else{
				    $('.pwd_error').hide();
				    pwd_error=true;
				}
            });
            $('form').submit(function(){});
        })
    </script>
{% endblock head %}
{% block body %}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ upwd }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock body %}




templates/df_user/register.html
{%extends 'base_foot.html'%}
{%block head%}
    <script type="text/javascript" src="/static/js/register.js"></script>
{%endblock head%}
{%block body%}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post">
					{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" >
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%endblock body%}

templates/df_user/user_center_info.html
{% extends 'df_user/user_center_top.html' %}

{% block b %}
        <div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user_name }}</li>
							<li><span>联系方式：</span>{{ user_email }}</li>
							<li><span>联系地址：</span>{{ user_email }}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
                    <ul class="goods_type_list clearfix">
                        {% for g in goods_list %}
                        <li>
                            <a href="/{{ g.id }}"><img src="/static/{{ g.gpic }}"></a>
                            <h4><a href="/{{ g.id }}">{{ g.gtitle }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ g.gprice }}</span>
                                <span class="unit">{{ g.gunit }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                        {% endfor %}

			        </ul>
		        </div>
		</div>
{% endblock b %}

templates/df_user/user_center_order.html
{% extends 'df_user/user_center_top.html' %}

{% block b %}
<div class="right_content clearfix">
    <h3 class="common_title2">全部订单</h3>
    {% for orderinfo in orderlist %}
    <ul class="order_list_th w978 clearfix">
        <li class="col01">{{orderinfo.odate}}</li>
        <li class="col02">订单号：{{orderinfo.oid}}</li>
        {% if orderinfo.oIsPay %}
        <li class="col02 stress">已支付</li>
        {% else %}
        <li class="col02 stress">未支付</li>
        {% endif %}
    </ul>
    <table class="order_list_table w980">
        <tbody>
        <tr>
            <td width="55%">
                {% for item in orderinfo.orderdetailinfo_set.all %}
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="/static/{{item.goods.gpic}}"></li>
                    <li class="col02">{{item.goods.gtitle}}<em><span>{{item.price}}</span>元/{{item.goods.gunit}}</em>
                    </li>
                    <li class="col03">{{item.count}}个</li>
                    <li class="col04"></li>
                </ul>
                {% endfor %}
            </td>
            <td width="15%">{{orderinfo.ototal}}元</td>
            {% if orderinfo.oIsPay %}
            <td width="15%">已付款</td>
            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
            {% else %}
            <td width="15%">未付款</td>
            <td width="15%"><a href="/order/pay&{{orderinfo.oid}}/" class="oper_btn">去付款</a></td>
            {% endif %}
        </tr>
        </tbody>
    </table>
    {% endfor %}
    <div class="pagenation">
        {% if orderlist.has_previous %}
        <a href="/user/user_center_order&{{orderlist.previous_page_number}}/">
            上一页
        </a>
        {% endif %}
{#    分页 ： plist 一共多少页  pageid 当前页  orderlist paginator按照两个一页，分的，页的指向对象  #}
    {% if lenn < 4  %}
        {% if lenn == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        {% elif lenn == 2 %}
            {% if pageid == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            {% else %}
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            {% endif %}
        {% elif lenn == 3%}

            {% if pageid == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            <a href="/user/user_center_order&{{nextt}}/" >{{nextt}}</a>
            {% elif pageid == 2 %}
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            {% else %}
            <a href="/user/user_center_order&{{pree}}/" >{{pree}}</a>
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            {% endif %}
        {% endif %}
    {% elif pageid < lenn %}
        {% if orderlist.has_previous  %}
        <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
        {% else %}
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
        <a href="/user/user_center_order&{{nextt}}/" >{{nextt}}</a>
        {% endif %}
    {% else %}
        <a href="/user/user_center_order&{{pree}}/" >{{pree}}</a>
        <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
    {% endif %}


        {% if orderlist.has_next %}
        <a href="/user/user_center_order&{{orderlist.next_page_number}}/">下一页></a>
        {% endif %}
    </div>
</div>

{% endblock b %}

templates/df_user/user_center_site.html
{% extends 'df_user/user_center_top.html' %}

{% block b %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uaddress }}  （{{ user.usjname }} 收） {{ user.umobile }}</dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{ user.usjname }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{ user.uaddress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian" value="{{ user.upost }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{ user.umobile }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
{% endblock b %}

templates/df_user/user_center_top.html
{% extends 'base.html' %}


{% block left_list  %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info" {% if option == 1 %} class="active" {% endif %}>· 个人信息</a></li>
				<li><a href="/user/order" {% if option == 2 %} class="active" {% endif %}>· 全部订单</a></li>
				<li><a href="/user/site" {% if option == 3 %} class="active" {% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		{% block b %}

		{% endblock b %}
	</div>
{% endblock left_list %}